greet = "Hi, {name}, I am bot who using OpenAI API. Give me a question and I will response"
menu = "Menu"
gen_text = "Type a text to generate an answer"
gen_image = "Type a text to generate an image"
gen_exit = "If you want exit chatgpt dialogue press button below"
gen_error = "Try again"
text_watermark = "\n_______________________________________\nCreate by @openaigpt_3_bot"
img_watermark = "Create by @openaigpt_3_bot"
gen_wait = "Please wait"
help = "I dont know"
help_exit = "If you want exit press button below"

err = "Sorry, error. Try later"